//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace winforms
{
    using System;
    using System.Collections.Generic;
    
    public partial class Students
    {
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Group { get; set; }
        public int Number { get; set; }
        public double Avg_Grade { get; set; }
        public bool Budget { get; set; }
    
        public virtual Groups Groups { get; set; }
    }
}
